### ISSUE TITLE
[🔥 Refactor] 검색 API를 개선한다.

### ISSUE THREAD

**Issue by greeng00se** [teco-chat/backend#88]
## **🌈 추가할 기능에 대한 설명**
현재 검색 API가 조건이 너무 많아서 프론트에서 처리하기 복잡하고, 사용 과정도 복잡한데
이를 진짜 검색창 처럼 아무렇게나 입력해도 적당히 검색되게 하는건 어때?

**Comment by shin-mallang** [comment]
음 제목 + 내용 전체를??

**Comment by greeng00se** [comment]
예압!
